source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chromedriver-helper'
gem 'prickle'
gem 'pry'
gem 'pretty_face'
gem 'randomstring'
